Landing Page
atlp-rwanda/rca-phantom-team2-fe pull request #6
Opened 2023-04-19 12:39 UTC by kelliaUmuhire

#### What does this PR do?
* Adds landing page
#### Description of Task to be completed?
* Add responsive landing page with skeleton loader
#### How should this be manually tested?
* Clone the repo
* Run `npm install` to install modules
* Run `npm start`
* Go to `localhost:3000`
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker/Trello stories?
* [Link](https://trello.com/c/YvPmmAVB)

2023-04-20 13:00 UTC, degide requested changes
Revise the page responsiveness in mobile. Also I think the page can be allowed to scroll vertically in order to show the image in smaller screens.

Please check slack channel for the screenshots.

2023-05-02 09:48 UTC, degide approved these changes

2023-05-02 09:54 UTC, MikeManzi approved these changes

2023-05-02 10:24 UTC, jacques-twizeyimana approved these changes
LGTM!

2023-05-02 10:24 UTC, merged