Reset Password
atlp-rwanda/rca-phantom-team2-fe pull request #8
Opened 2023-04-27 12:58 UTC by MikeManzi

2023-05-02 10:27 UTC, jacques-twizeyimana requested changes
Resolve conflicts in Navbar.tsx

2023-05-04 01:48 UTC, jacques-twizeyimana approved these changes
LGTM

2023-05-04 09:32 UTC, kelliaUmuhire approved these changes

2023-05-04 11:04 UTC, freddykaberuka reviewed
Good Job @MikeManzi,
however, you should have implemented it with Redux

2023-05-04 11:07 UTC, merged